spring.application.name=identity-service

# Connection to Auth database (Port 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection to Restaurant database (Port 5434)
spring.datasource.url=jdbc:postgresql://localhost:5434/restaurant_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true